replicaCount: 1

image:
  pullPolicy: Always


ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: api.chainstatus.org
      paths:
        - path: /render(/|$)(.*)
          pathType: Prefix
  tls:
    - secretName: cloudflare-tls
      hosts:
        - api.chainstatus.org

parameters:
  ENVIRONMENT: production
  SERVER_PORT: 80
  SERVER_READ_TIMEOUT: 60
  WS_WEB3_URL: https://data-seed-prebsc-2-s3.binance.org:8545
  BONBONUS_CONTRACT_ADDRESS: 0x5d388Aa431271a76d824DB4eddbE996C321F3887