replicaCount: 1

image:
  pullPolicy: Always


ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: api.chainstatus.org
      paths:
        - path: /ml(/|$)(.*)
          pathType: Prefix
  tls:
    - secretName: cloudflare-tls
      hosts:
        - api.chainstatus.org

parameters:
  PORT: 80