replicaCount: 1

image:
  pullPolicy: Always

ingress:
  hosts:
    - host: api.chainstatus.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cloudflare-tls
      hosts:
        - api.chainstatus.org

parameters:
  ENVIRONMENT: production
  PORT: 80
  CHAINLINK_ORACLE_API_KEY: 2cfr34VGcZ6R9ep9MnI0
  MORALIS_API_KEY: OGqKjTlLKLbFRgO4FkrKk9PpuncN7WjwHYXgEtkaubJmQQ2XoqTq6gLFfAO4P2oc
  BONBONUS_CONTRACT_ADDRESS: 0x84405765be8EBF19e6D365F27Eae48653c105BBd
  RPC_URL: https://aged-flashy-dream.bsc-testnet.discover.quiknode.pro/6a3a33e6439e6c74d92f15c89fadc3dfd43999e0/